-- EDA

-- Here we are just going to explore the data and find trends or patterns or anything interesting like outliers

-- normally when you start the EDA process you have some idea of what you're looking for

-- with this info we are just going to look around and see what we find!


SELECT *
FROM LAYOFFS2
;

-- MAX TOTAL LAID OFF IN LAYOFFS_STAGE 2 --
SELECT max(TOTAL_LAID_OFF)
FROM LAYOFFS2
;

-- companies had 1 which is basically 100 percent of they company laid off --
SELECT *
FROM layoffs2
WHERE PERCENTAGE_LAID_OFF = 1
;

-- DATE STARTED  AND ON GOING DATE --
SELECT min(`DATE`), max(`DATE`)
FROM LAYOFFS2
;

-- THE SUM OF TOTAL LAID OFF BY COMPANY --
SELECT COMPANY, SUM(TOTAL_LAID_OFF)
FROM LAYOFFS2
GROUP BY COMPANY
ORDER BY 2 DESC
;

-- THE SUM OF TOTAL LAID OFF BY INDUSTRY --
SELECT INDUSTRY, SUM(TOTAL_LAID_OFF)
FROM LAYOFFS2
GROUP BY INDUSTRY
ORDER BY 2 DESC
;

-- THE SUM OF TOTAL LAID OFF BY COUNTRY --
SELECT COUNTRY, SUM(TOTAL_LAID_OFF)
FROM LAYOFFS2
GROUP BY COUNTRY
ORDER BY 2 DESC
;

-- SUM OF TOTAL LAID OFF PER YEAR --
SELECT year(`DATE`), SUM(TOTAL_LAID_OFF)
FROM LAYOFFS2
GROUP BY year(`DATE`)
ORDER BY 1 DESC
;

-- SUM OF TOTAL LAID OFF BY STAGE --
SELECT STAGE, SUM(TOTAL_LAID_OFF)
FROM LAYOFFS2
GROUP BY STAGE
ORDER BY 2 DESC
;

-- SUM OF PERCENTAGE LAID OFF BY COMPANY --
SELECT COMPANY, SUM(PERCENTAGE_LAID_OFF)
FROM LAYOFFS2
GROUP BY COMPANY
ORDER BY 2 DESC
;


-- TOTAL OF LAID OFFS BASED OF EVERY MONTH --
SELECT substring(`DATE`, 1, 7), sum(TOTAL_LAID_OFF)
FROM LAYOFFS2
WHERE `DATE` IS NOT NULL
group by substring(`DATE`, 1, 7)
ORDER BY 1
;

-- ROLLING TOTAL OF LAID OFFS BASED OF EVERY MONTH --
WITH ROLLING_TOTAL AS
(
SELECT substring(`DATE`, 1, 7) AS `MONTH`, sum(TOTAL_LAID_OFF) AS TOTAL_OFF
FROM LAYOFFS2
GROUP BY `MONTH`
)

SELECT  `MONTH`, TOTAL_OFF, sum(TOTAL_OFF) OVER( order by `MONTH`) AS ROLLING_TOTAL_MONTH
FROM ROLLING_TOTAL
;

-- TOTAL LAID OFF OF COMPANY PER YEAR --

SELECT year(`DATE`), SUM(TOTAL_LAID_OFF)
FROM LAYOFFS2
GROUP BY YEAR(`DATE`)
;

-- TOP 3 COMPANY TOTAL_LAID_OFF PER YEAR--

WITH TOP_3 AS
(
SELECT COMPANY, year(`DATE`) AS `YEAR`, SUM(TOTAL_LAID_OFF) AS TOTAL_LAID
FROM LAYOFFS2
GROUP BY COMPANY, YEAR(`DATE`)

),
COMPANY_YEAR_RANK AS
(
SELECT *, dense_rank() OVER(PARTITION BY `YEAR` ORDER BY TOTAL_LAID DESC) AS RANKING
FROM TOP_3
WHERE `YEAR` IS NOT NULL

)

SELECT *
FROM COMPANY_YEAR_RANK
WHERE RANKING <=3
;

